### PR TITLE
Initial task service API doc

### PR DESCRIPTION
**Pull request by awm33**
### Motivation

In order to communicate what the task service is and flesh out its interaction with other components, I thought creating a doc would help.
### Implementation Notes

This is just some initial documentation. Based on a subset of fields I've used on a couple other task management systems. I hope to grow it to be more detailed and cover more endpoints over time. The schema can change depending on needs, like adding a `user_id` field with a user id, cookie id, or slug for instance.

I've also used a `task_events` table and a `host` column on task to record the worker on the other implementations, those may be nice to have here. This also does not include exponential backoff on task retries. That can be pretty implemented if needed.

### CODE REVIEW

**Comment by dhimmel** [comment]
@awm33 do you want to suggest some reviewers from cognoma/cognoma#2?

**Comment by awm33** [comment]
I think @dcgoss had a good understanding of what the task-service does during the meetup tuesday and has commented on related issues.

@aelkner @cgreene may want to look as well

**Comment by dcgoss** [comment]
I'll take a look

**Comment by aelkner** [comment]
👍

**Pull request merged**
